url: https://tcfnc.github.io
baseurl: "" 

# Site settings
title: TCFNC - Telugu Christian Fellowship of North Carolina
email: joelravi2001@yahoo.com 
description: "Telugu Christian Fellowship is here to gather together to worship our Lord, encourage our fellow believers, & serve our community with the love of Christ."


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/TCFNorthCarolina/

# Postal address (add as many lines as necessary)
address:
#  - line: 
  - line: Raleigh, NC
  - line: Cary, NC
  - line: Durham, NC

# Build settings
markdown: kramdown
permalink: pretty
